# Generated by Django 4.2.11 on 2024-05-07 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0002_entry'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='date_add',
            new_name='date_added',
        ),
    ]
